### ISSUE TITLE
Too much package in requirements.txt

### ISSUE THREAD

**Issue by vuthanhdatt** [vietzerg/Scrape-Finance-Data-v2#2]
Why there is too much package in requirements.txt, for example cryptography==2.9.2 package i don't know what is this package used for?

**Comment by vietzerg** [comment]
It's because Scrapy depends on it. From [Scrapy installation page](https://docs.scrapy.org/en/latest/intro/install.html):

> Things that are good to know
> Scrapy is written in pure Python and depends on a few key Python packages (among others):
> - lxml, an efficient XML and HTML parser
> - parsel, an HTML/XML data extraction library written on top of lxml,
> - w3lib, a multi-purpose helper for dealing with URLs and web page encodings
> - twisted, an asynchronous networking framework
> - cryptography and pyOpenSSL, to deal with various network-level security needs

That said, the `requirements.txt` definitely needs cleaning to reduce build time for Docker. I just haven't got the time to look into that yet.
